version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:0-7.0
    volumes:
      - ..:/workspace:cached
    network_mode: service:localstack
    command: sleep infinity
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566/
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack-data: